language: python
python:
  - "2.7"
  - "3.5"
install:
  - pip install --upgrade pip setuptools wheel
  - pip install --only-binary=numpy, scipy numpy scipy
  - pip install -U scikit-learn
  - pip install git+https://github.com/automl/pysmac.git
script:
  - python smackdown.py
  - python hyperparameter_optimizer.py
